print("Welcome to the Hero Name Generator.")
city = input("What's the name of the city you want to protect?\n")
power = input("What's your power?\n")
gender = input("What's your gender?\n")
print("Your Hero name could be " + city + " " + power + "-" + gender)